server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaidIdk/EXAMEN-MICROSERVICIOS.git
          searchPaths: config-data
          default-label: EXAMEN-MICROSERVICIOS
  security:
    user:
      name: root
      password: 123456
